### ISSUE TITLE
Орфография в коде

### ISSUE THREAD

**Issue by allustin** [silverbulleters/sonar-1c-bsl-public#10]
пора наверное опубликовать наработки в следующем релизе

**Comment by allustin** [comment]
в очередную версию включено:

* проверка орфографии в имени метода каждого слова 
https://sonar.silverbulleters.org/coding_rules#rule_key=bsl%3ASpellCheckMethodName

следующая на очереди орфография в тексте модуля

* https://sonar.silverbulleters.org/coding_rules#rule_key=bsl%3AACC_000000036

пока идет отладка словаря орфографии на технический сленг

P.S. Как вы понимаете без всяких Word'ов и остального - всё включено в плагин

**Comment by JohnyDeath** [comment]
А откуда словарь? Он, как я понял, не распознает букву "е", когда она "ё".
Повылезали слова типа "Еще", "Учета"

**Comment by nixel2007** [comment]
@allustin может будем подбивать единый чейнджлог при выходе новой версии? Эта проверка не в релизе, тем более не до конца отлажена. не хорошо как-то.

**Comment by allustin** [comment]
@nixel2007 предлагаю действительно перейти на релизный план #11 и уже с помощью них подбивать выход версий.

**Comment by JohnyDeath** [comment]
![image](https://cloud.githubusercontent.com/assets/5936030/22196218/23e48fb4-e15d-11e6-8df8-3767ff1b2226.png)

Вроде как нигде нет ошибок. Спелл-чекер русскую грамматику знает не очень хорошо или же его надо как-то обучать.

**Comment by nixel2007** [comment]
@JohnyDeath пропустили обработку директив компиляции. Поправим. Спасибо!

/cc @allustin

**Comment by nixel2007** [comment]
Если коротко - спелл-чекер переключился на английскую грамматику.

**Comment by JohnyDeath** [comment]
Тогда все объясняет, а то там столько накидало..

**Comment by allustin** [comment]
реализовано включая минус слова - плюс в релизе 1.6 обновлен еще и словарь
