### ISSUE TITLE
Ошибка анализатора

### ISSUE THREAD

**Issue by theshadowco** [silverbulleters/sonar-1c-bsl-public#12]
Анализатор (актуальная версия на данный момент) падает при разборе 
`2269: Функция ЗагрузитьАдресныйКлассификаторРоссия(КодСтраны, Знач КодАдресногоОбъекта, АдресныеСведения, ПутьКДаннымНаСервере, ПротоколЗагрузки, Обновление = ЛОЖЬ)`
` 2270: `
` 2271:  #Если Клиент И Не Клиент Тогда`
` 2272: `
`  -->    ЗагрузитьАдресныйКлассификаторРоссия(КодСтраны, Знач КодАдресногоОбъекта, АдресныеСведения, ПутьКДаннымНаСервере, ПротоколЗагрузки);`
` 2274: `
` 2275:  #КонецЕсли`

Понятно, что написано с ошибкой, но падать все-таки не стоит

**Comment by nixel2007** [comment]
А что делать-то? :)
AST строится по определенным правилам, в данном случае AST построиться не смогло из-за синтаксической ошибки.

Проверки используют AST. Нет AST - нет проверок :)

**Comment by theshadowco** [comment]
В принципе норм, у меня просто анализ совсем падал, думал из-за этого. По факту - упал из-за того, что я создал копию правил и выключил в нем несколько штук. Вернул на сонар вей, все восстановилось.
