### ISSUE TITLE
Опубликовать список правил которые уже есть

### ISSUE THREAD

**Issue by allustin** [silverbulleters/sonar-1c-bsl-public#2]
Сейчас у нас 164 проверку - могу ошибаться, но порядок цифр такой.
Если кто-то захочет публично попросить проверку - ему нужно знать какая проверка уже есть, чтобы не творить дубликаты

**Comment by allustin** [comment]
может кстати и не нужно... но подумать стоит

**Comment by nixel2007** [comment]
Опубликовано, информация доступа в readme
