### ISSUE TITLE
Руссификация правил

### ISSUE THREAD

**Issue by theshadowco** [silverbulleters/sonar-1c-bsl-public#6]
Я как разработчик
Хочу иметь руссифицированные описания правил проверки ошибок

**Comment by nixel2007** [comment]
Стоит в очереди на разработку. Спасибо :) 
Будем делать, от многих такой запрос.

**Comment by allustin** [comment]
@theshadowco тут такое дело - сразу скажу, за основу выбрана концепция что изначально правила на английском ;-) для популяризации 1С за рубежом.

А локализацию сделаем - там не долго.

**Comment by nixel2007** [comment]
Реализовано в 1.2
