### ISSUE TITLE
Правило "обращение через две и более точек" в запросе.

### ISSUE THREAD

**Issue by JohnyDeath** [silverbulleters/sonar-1c-bsl-public#8]
Не должны срабатывать конструкции "Значение(Справочник.Вид1.Ссылка1)"
Вот пример ложного срабатывания: https://sonar.silverbulleters.org/component/index?id=johnydeath-microz%3Asrc%2Fconfiguration%2FCommonModules%2FОбщегоНазначенияВызовСервера_МЗ%2FExt%2FModule.bsl&line=404

**Comment by nixel2007** [comment]
Исправлено в 1.2
