### ISSUE TITLE
Почему ругается на наименование com-объекта?

### ISSUE THREAD

**Issue by JohnyDeath** [silverbulleters/sonar-1c-bsl-public#9]
На код
```bsl
shell=Новый COMОбъект("WScript.Shell");
```
Ругается таким вот правилом:

> Rename this 'shell' variable to match the regular expression ([a-zа-яё]*_)?[A-ZА-ЯЁ]([a-zA-Zа-яёА-ЯЁ0-9_]*[a-zA-Zа-яёА-ЯЁ0-9])?+
> Sharing some naming conventions is a key point to make it possible for a team to efficiently collaborate. This rule allows to check that all variable names match a provided regular expression.

**Comment by nixel2007** [comment]
Это нормально. По стандартам 1с переменная должна быть в TitleCase. Нами было добавлено еще иметь префикс. Общий вид разрешаемого имени:
* префикс строчными буквами, отделанный нижним подчеркиванием (необязательно) 
* TtitleCase

P.s. Там где-то ещё в тайтл кейсе должны быть цифры  странно, что их нет в тексте ошибки.

**Comment by JohnyDeath** [comment]
Извиняюсь. Почему-то подумал, что ругается на то, что в кавычках.

Русский - наш родной язык! ;)
